### ISSUE TITLE
Error in Step 5: Session 3

### ISSUE THREAD

**Issue by alexscotttonge** [makersacademy/escape-precourse-issues#12]
Getting this error: 

directory.rb:29:in `print_footer': undefined local variable or method `students' for main:Object (NameError)
	from directory.rb:34:in `<main>'

When running the program following this page: http://makersacademy.teachable.com/courses/172320/lectures/2584160

I can get it to run correctly if I replace 'names' with 'students':

def print_header
  puts "The students of Villains Academy"
  puts "------------"
end

def print(students)
  students.each do |name|
    puts name
  end
end

def print_footer(students)
  puts "Overall we have #{students.count} great students"
end
#nothing happens until we call the methods
print_header
print(students)
print_footer(students)

I think may be an error from the instructions.

**Comment by nikeshashar** [comment]
Have you got a link to your code?
